package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libffi-dev
    version: '>=0'
  - category: alpine
    name: expat-dev
    version: '>=0'
  - category: alpine
    name: doxygen
    version: '>=0'
  - category: alpine
    name: xmlto
    version: '>=0'
  - category: alpine
    name: graphviz
    version: '>=0'
  - category: alpine
    name: grep
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: bash
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
