package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: font-util-dev
    version: '>=0'
  - category: alpine
    name: font-util
    version: '>=0'
  - category: alpine
    name: bdftopcf
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
