package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: bzip2-dev
    version: '>=0'
  - category: alpine
    name: curl-dev
    version: '>=0'
  - category: alpine
    name: expat-dev
    version: '>=0'
  - category: alpine
    name: libarchive-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: libuv-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: rhash-dev
    version: '>=0'
  - category: alpine
    name: xz-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
