package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: gtk+-dev
    version: '>=0'
  - category: alpine
    name: mariadb-connector-c-dev
    version: '>=0'
  - category: alpine
    name: intltool
    version: '>=0'
  - category: alpine
    name: libusb-compat-dev
    version: '>=0'
  - category: alpine
    name: libxpm-dev
    version: '>=0'
  - category: alpine
    name: bluez-dev
    version: '>=0'
  - category: alpine
    name: libical-dev
    version: '>=0'
  - category: alpine
    name: postgresql-dev
    version: '>=0'
  - category: alpine
    name: sqlite-dev
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: gettext-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
