package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: libgcrypt-dev
    version: '>=0'
  - category: alpine
    name: libgpg-error-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
