package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: meson
    version: '>=0'
  - category: alpine
    name: spice-protocol
    version: '>=0'
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: gdk-pixbuf-dev
    version: '>=0'
  - category: alpine
    name: pixman-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: libjpeg-turbo-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: opus-dev
    version: '>=0'
  - category: alpine
    name: gstreamer-dev
    version: '>=0'
  - category: alpine
    name: gst-plugins-base-dev
    version: '>=0'
  - category: alpine
    name: orc-dev
    version: '>=0'
  - category: alpine
    name: lz4-dev
    version: '>=0'
  - category: alpine
    name: cyrus-sasl-dev
    version: '>=0'
  - category: alpine
    name: py3-six
    version: '>=0'
  - category: alpine
    name: py3-parsing
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
