package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: cmake
    version: '>=0'
  - category: alpine
    name: doxygen
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: ncurses
    version: '>=0'
  - category: alpine
    name: pcre2-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
