package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: dbus-glib-dev
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: py3-sphinx
    version: '>=0'
  - category: alpine
    name: py3-sphinx_rtd_theme
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
