package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: gtest=1.10.0-r1
    version: '>=0'
  - category: alpine
    name: gmock=1.10.0-r1
    version: '>=0'
  - category: alpine
    name: cmake
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
