image: "quay.io/mocaccino/micro-toolchain:latest"
prelude:
  - |
    luet install repository/mocaccino-musl-universe && \
    luet install \
    utils/file development/pax-utils utils/tar development/musl-utils libs/libressl development/abuild \
    system/luet-develop utils/autoconf utils/curl development/make libs/zlib vcs/git \
    development/automake development/pkg-config development/m4 \
    system/musl-compat && \
    ln -s /bin/gcc /bin/cc
  - mkdir /build
  - cp -rfv env /build/env