package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: utmps-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: libutempter-dev
    version: '>=0'
  - category: alpine
    name: ncurses
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
