package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: scons
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: libcap-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
