package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: gperf
    version: '>=0'
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: kmod-dev
    version: '>=0'
  - category: alpine
    name: gobject-introspection-dev
    version: '>=0'
  - category: alpine
    name: util-linux-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
