package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-lts-dev=5.4.80-r0
    version: '>=0'
  - category: alpine
    name: bash
    version: '>=0'
  - category: alpine
    name: coreutils
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
