package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: linux-pam-dev
    version: '>=0'
  - category: alpine
    name: check-dev
    version: '>=0'
  - category: alpine
    name: ckbcomp
    version: '>=0'
  - category: alpine
    name: xkeyboard-config
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
