package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-lts-dev
    version: '>=0'
  - category: alpine
    name: iptables-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
