package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: iptables
    version: '>=0'
  - category: alpine
    name: perl-net-dns-resolver-mock
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
