package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: sed
    version: '>=0'
  - category: alpine
    name: libxslt
    version: '>=0'
  - category: alpine
    name: libmnl-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: xz-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
