package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: openssl
    version: '>=0'
  - category: alpine
    name: lua5.3
    version: '>=0'
  - category: alpine
    name: lua5.3-lzlib
    version: '>=0'
  - category: alpine
    name: scdoc
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: zlib-static
    version: '>=0'
  - category: alpine
    name: openssl-libs-static
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: lua5.3-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
