package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: pcre-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: bzip2-dev
    version: '>=0'
  - category: alpine
    name: lua5.3-dev
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: openldap-dev
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: sqlite-dev
    version: '>=0'
  - category: alpine
    name: libev-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
