package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libburn-dev
    version: '>=0'
  - category: alpine
    name: libisofs-dev
    version: '>=0'
  - category: alpine
    name: acl-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: libedit-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
