package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: util-linux-dev
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: autoconf-archive
    version: '>=0'
  - category: alpine
    name: expat-dev
    version: '>=0'
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: libsm-dev
    version: '>=0'
  - category: alpine
    name: libx11-dev
    version: '>=0'
  - category: alpine
    name: xmlto
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
