package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libpcap-dev
    version: '>=0'
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: libnetfilter_queue-dev
    version: '>=0'
  - category: alpine
    name: libnfnetlink-dev
    version: '>=0'
  - category: alpine
    name: libdnet-dev
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
