package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: spirv-headers
    version: '>=0'
  - category: alpine
    name: spirv-tools=2020.3-r0
    version: '>=0'
  - category: alpine
    name: cmake
    version: '>=0'
  - category: alpine
    name: samurai
    version: '>=0'
  - category: alpine
    name: python3
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
