package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: libpng-dev
    version: '>=0'
  - category: alpine
    name: libjpeg-turbo-dev
    version: '>=0'
  - category: alpine
    name: expat-dev
    version: '>=0'
  - category: alpine
    name: fontconfig-dev
    version: '>=0'
  - category: alpine
    name: libsm-dev
    version: '>=0'
  - category: alpine
    name: libxext-dev
    version: '>=0'
  - category: alpine
    name: cairo-dev
    version: '>=0'
  - category: alpine
    name: pango-dev
    version: '>=0'
  - category: alpine
    name: gmp-dev
    version: '>=0'
  - category: alpine
    name: freetype-dev
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: swig
    version: '>=0'
  - category: alpine
    name: m4
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: libxaw-dev
    version: '>=0'
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: lua5.3-dev
    version: '>=0'
  - category: alpine
    name: libltdl
    version: '>=0'
  - category: alpine
    name: tcl
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: bash
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
