package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: cairo-dev
    version: '>=0'
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: cmake
    version: '>=0'
  - category: alpine
    name: fontconfig-dev
    version: '>=0'
  - category: alpine
    name: gobject-introspection-dev
    version: '>=0'
  - category: alpine
    name: lcms2-dev
    version: '>=0'
  - category: alpine
    name: libjpeg-turbo-dev
    version: '>=0'
  - category: alpine
    name: libpng-dev
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: openjpeg-dev
    version: '>=0'
  - category: alpine
    name: openjpeg-tools
    version: '>=0'
  - category: alpine
    name: tiff-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
