package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libxau-dev
    version: '>=0'
  - category: alpine
    name: xcb-proto
    version: '>=0'
  - category: alpine
    name: libpthread-stubs
    version: '>=0'
  - category: alpine
    name: libxdmcp-dev
    version: '>=0'
  - category: alpine
    name: libxslt
    version: '>=0'
  - category: alpine
    name: python3
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
