package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: libnl3-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
