package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: xorg-server-dev
    version: '>=0'
  - category: alpine
    name: spice-dev
    version: '>=0'
  - category: alpine
    name: xorg-server
    version: '>=0'
  - category: alpine
    name: xorgproto
    version: '>=0'
  - category: alpine
    name: libpciaccess-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
