package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: xorgproto
    version: '>=0'
  - category: alpine
    name: libx11-dev
    version: '>=0'
  - category: alpine
    name: libxext-dev
    version: '>=0'
  - category: alpine
    name: meson
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
