package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: libx11-dev
    version: '>=0'
  - category: alpine
    name: libao-dev
    version: '>=0'
  - category: alpine
    name: libsamplerate-dev
    version: '>=0'
  - category: alpine
    name: libxrandr-dev
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: libxcursor-dev
    version: '>=0'
  - category: alpine
    name: libtasn1-dev
    version: '>=0'
  - category: alpine
    name: nettle-dev
    version: '>=0'
  - category: alpine
    name: gnutls-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
