package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: nettle-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: libtasn1-dev
    version: '>=0'
  - category: alpine
    name: p11-kit-dev
    version: '>=0'
  - category: alpine
    name: libunistring-dev
    version: '>=0'
  - category: alpine
    name: texinfo
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
