package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: docbook-xsl
    version: '>=0'
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: libxslt
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: po4a
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
