package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: augeas-dev
    version: '>=0'
  - category: alpine
    name: ruby-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
