package_dir: /luetbuild/pkg/{{.Values.name}}
env:
  - CFLAGS="-g -O2 -I/include -I/usr/include -fPIC"
steps:
  - sh build.sh
requires:
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: libunistring-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
