package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libxrandr-dev
    version: '>=0'
  - category: alpine
    name: util-macros
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
