package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: meson
    version: '>=0'
  - category: alpine
    name: libtasn1-dev
    version: '>=0'
  - category: alpine
    name: libffi-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
