package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: asciidoctor
    version: '>=0'
  - category: alpine
    name: libcap-dev
    version: '>=0'
  - category: alpine
    name: texinfo
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
