package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libmnl-dev
    version: '>=0'
  - category: alpine
    name: bash
    version: '>=0'
  - category: alpine
    name: jansson-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
