package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: cmake
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: clang
    version: '>=0'
  - category: alpine
    name: llvm-dev>=10
    version: '>=0'
  - category: alpine
    name: llvm-static
    version: '>=0'
  - category: alpine
    name: samurai
    version: '>=0'
  - category: alpine
    name: python3
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
