package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: perl-dev
    version: '>=0'
  - category: alpine
    name: perl-test-requires
    version: '>=0'
  - category: alpine
    name: perl-http-message
    version: '>=0'
  - category: alpine
    name: perl-try-tiny
    version: '>=0'
  - category: alpine
    name: perl-uri
    version: '>=0'
  - category: alpine
    name: perl-test-mocktime
    version: '>=0'
  - category: alpine
    name: perl-module-build-tiny
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
