package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: wayland-dev
    version: '>=0'
  - category: alpine
    name: wayland-protocols
    version: '>=0'
  - category: alpine
    name: libxcb-dev
    version: '>=0'
  - category: alpine
    name: meson
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
