package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: byacc
    version: '>=0'
  - category: alpine
    name: curl-dev
    version: '>=0'
  - category: alpine
    name: czmq-dev
    version: '>=0'
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: gnutls-dev
    version: '>=0'
  - category: alpine
    name: hiredis-dev
    version: '>=0'
  - category: alpine
    name: krb5-dev
    version: '>=0'
  - category: alpine
    name: libdbi-dev
    version: '>=0'
  - category: alpine
    name: libestr-dev
    version: '>=0'
  - category: alpine
    name: libfastjson-dev
    version: '>=0'
  - category: alpine
    name: libgcrypt-dev
    version: '>=0'
  - category: alpine
    name: liblogging-dev
    version: '>=0'
  - category: alpine
    name: liblognorm-dev
    version: '>=0'
  - category: alpine
    name: libmaxminddb-dev
    version: '>=0'
  - category: alpine
    name: libnet-dev
    version: '>=0'
  - category: alpine
    name: librelp-dev
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: mariadb-connector-c-dev
    version: '>=0'
  - category: alpine
    name: net-snmp-dev
    version: '>=0'
  - category: alpine
    name: postgresql-dev
    version: '>=0'
  - category: alpine
    name: py3-docutils
    version: '>=0'
  - category: alpine
    name: rabbitmq-c-dev
    version: '>=0'
  - category: alpine
    name: util-linux-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
