package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: ruby=2.7.2-r1
    version: '>=0'
  - category: alpine
    name: gmp-dev
    version: '>=0'
  - category: alpine
    name: libucontext-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: gdbm-dev
    version: '>=0'
  - category: alpine
    name: readline-dev
    version: '>=0'
  - category: alpine
    name: libffi-dev
    version: '>=0'
  - category: alpine
    name: coreutils
    version: '>=0'
  - category: alpine
    name: yaml-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
