package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: m4
    version: '>=0'
  - category: alpine
    name: util-linux
    version: '>=0'
  - category: alpine
    name: tiff-dev
    version: '>=0'
  - category: alpine
    name: jpeg-dev
    version: '>=0'
  - category: alpine
    name: libxslt-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
