package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: dbus-dev
    version: '>=0'
  - category: alpine
    name: docbook-xsl
    version: '>=0'
  - category: alpine
    name: vala
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: meson
    version: '>=0'
  - category: alpine
    name: py3-setuptools
    version: '>=0'
  - category: alpine
    name: bash-completion
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
