package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: atf-dev
    version: '>=0'
  - category: alpine
    name: lutok-dev
    version: '>=0'
  - category: alpine
    name: sqlite-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
