package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: perl-dev
    version: '>=0'
  - category: alpine
    name: perl-test-requires
    version: '>=0'
  - category: alpine
    name: perl-test-fatal
    version: '>=0'
  - category: alpine
    name: perl-yaml
    version: '>=0'
  - category: alpine
    name: perl-module-runtime
    version: '>=0'
  - category: alpine
    name: perl-sub-name
    version: '>=0'
  - category: alpine
    name: perl-pod-coverage
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
