package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: perl-dev
    version: '>=0'
  - category: alpine
    name: perl-html-parser
    version: '>=0'
  - category: alpine
    name: perl-digest-sha1
    version: '>=0'
  - category: alpine
    name: perl-netaddr-ip
    version: '>=0'
  - category: alpine
    name: perl-net-dns
    version: '>=0'
  - category: alpine
    name: perl-mail-dkim
    version: '>=0'
  - category: alpine
    name: perl-mime-base64
    version: '>=0'
  - category: alpine
    name: perl-time-hires
    version: '>=0'
  - category: alpine
    name: perl-libwww
    version: '>=0'
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: gnupg
    version: '>=0'
  - category: alpine
    name: re2c
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
