package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: cmake
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: raspberrypi-static
    version: '>=0'
  - category: alpine
    name: raspberrypi-libs
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
