package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: readline-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: lvm2-dev
    version: '>=0'
  - category: alpine
    name: bash
    version: '>=0'
  - category: alpine
    name: util-linux-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
