package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: lua5.3-dev
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: gtk+3.0-dev
    version: '>=0'
  - category: alpine
    name: libx11-dev
    version: '>=0'
  - category: alpine
    name: libxt-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
