package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: help2man
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
