package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: ruby
    version: '>=0'
  - category: alpine
    name: ruby-dev
    version: '>=0'
  - category: alpine
    name: ruby-rake
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
