package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: mandoc
    version: '>=0'
  - category: alpine
    name: db-dev
    version: '>=0'
  - category: alpine
    name: libasr-dev
    version: '>=0'
  - category: alpine
    name: libevent-dev
    version: '>=0'
  - category: alpine
    name: fts-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: flex-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
