package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: clang
    version: '>=0'
  - category: alpine
    name: llvm
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: icu-dev
    version: '>=0'
  - category: alpine
    name: libedit-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: util-linux-dev
    version: '>=0'
  - category: alpine
    name: openldap-dev
    version: '>=0'
  - category: alpine
    name: tcl-dev
    version: '>=0'
  - category: alpine
    name: perl-dev
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: llvm-dev
    version: '>=0'
  - category: alpine
    name: icu-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
