package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: mariadb-connector-c-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: postgresql-dev
    version: '>=0'
  - category: alpine
    name: sqlite-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: lzo-dev
    version: '>=0'
  - category: alpine
    name: acl-dev
    version: '>=0'
  - category: alpine
    name: postgresql
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
