package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: c-ares-dev
    version: '>=0'
  - category: alpine
    name: util-linux-dev
    version: '>=0'
  - category: alpine
    name: libwebsockets-dev
    version: '>=0'
  - category: alpine
    name: libxslt
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
