package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: gmp-dev
    version: '>=0'
  - category: alpine
    name: mpfr-dev>=4.1.0-r0
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
