package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: brotli-dev
    version: '>=0'
  - category: alpine
    name: gd-dev
    version: '>=0'
  - category: alpine
    name: geoip-dev
    version: '>=0'
  - category: alpine
    name: libmaxminddb-dev
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: libxslt-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: luajit-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: paxmark
    version: '>=0'
  - category: alpine
    name: pcre-dev
    version: '>=0'
  - category: alpine
    name: perl-dev
    version: '>=0'
  - category: alpine
    name: pkgconf
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
