package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libcap-dev
    version: '>=0'
  - category: alpine
    name: keyutils-dev
    version: '>=0'
  - category: alpine
    name: krb5-dev
    version: '>=0'
  - category: alpine
    name: talloc-dev
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: samba-dev
    version: '>=0'
  - category: alpine
    name: py3-docutils
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
