package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: perl-dev
    version: '>=0'
  - category: alpine
    name: perl-file-remove
    version: '>=0'
  - category: alpine
    name: perl-module-build
    version: '>=0'
  - category: alpine
    name: perl-module-scandeps
    version: '>=0'
  - category: alpine
    name: perl-yaml-tiny
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
