package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: cyrus-sasl-dev
    version: '>=0'
  - category: alpine
    name: memcached-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
