package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: util-linux-dev
    version: '>=0'
  - category: alpine
    name: libsodium-dev
    version: '>=0'
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: asciidoc
    version: '>=0'
  - category: alpine
    name: xmlto
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
