package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: pciutils-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: libnl-dev
    version: '>=0'
  - category: alpine
    name: gettext-dev
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: autoconf-archive
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
