package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: file
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: bsd-compat-headers
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: dahdi-linux-dev
    version: '>=0'
  - category: alpine
    name: newt-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
