package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: popt-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: libexecinfo-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: fuse-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: cryptsetup-dev
    version: '>=0'
  - category: alpine
    name: json-c-dev
    version: '>=0'
  - category: alpine
    name: net-snmp-dev
    version: '>=0'
  - category: alpine
    name: curl-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
