package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: net-snmp-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: gd-dev
    version: '>=0'
  - category: alpine
    name: libusb-compat-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
