package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: gettext
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
