package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: e2fsprogs-dev
    version: '>=0'
  - category: alpine
    name: libverto-dev
    version: '>=0'
  - category: alpine
    name: openldap-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: keyutils-dev
    version: '>=0'
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: perl
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
