package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: alsa-lib-dev
    version: '>=0'
  - category: alpine
    name: gsm-dev
    version: '>=0'
  - category: alpine
    name: speex-dev
    version: '>=0'
  - category: alpine
    name: speexdsp-dev
    version: '>=0'
  - category: alpine
    name: portaudio-dev
    version: '>=0'
  - category: alpine
    name: libsrtp-dev
    version: '>=0'
  - category: alpine
    name: libsamplerate-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
