package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: gmp-dev
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: texinfo
    version: '>=0'
  - category: alpine
    name: libunistring-dev
    version: '>=0'
  - category: alpine
    name: libffi-dev
    version: '>=0'
  - category: alpine
    name: gc-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
