package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: libxml2-utils
    version: '>=0'
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: intltool
    version: '>=0'
  - category: alpine
    name: itstool
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
