package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: meson
    version: '>=0'
  - category: alpine
    name: libpthread-stubs
    version: '>=0'
  - category: alpine
    name: eudev-dev
    version: '>=0'
  - category: alpine
    name: libpciaccess-dev
    version: '>=0'
  - category: alpine
    name: xmlto
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
