package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: yaml-dev
    version: '>=0'
  - category: alpine
    name: cython
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
