package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: augeas-dev
    version: '>=0'
  - category: alpine
    name: libgcrypt-dev
    version: '>=0'
  - category: alpine
    name: libnl3-dev
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: libxslt-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: pkgconfig
    version: '>=0'
  - category: alpine
    name: readline-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
