package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: speex-dev
    version: '>=0'
  - category: alpine
    name: libtheora-dev
    version: '>=0'
  - category: alpine
    name: libvorbis-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
