package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: openrc-dev
    version: '>=0'
  - category: alpine
    name: bsd-compat-headers
    version: '>=0'
  - category: alpine
    name: lua5.1-dev
    version: '>=0'
  - category: alpine
    name: lua5.2-dev
    version: '>=0'
  - category: alpine
    name: lua5.3-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
