package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: coreutils
    version: '>=0'
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: python3
    version: '>=0'
  - category: alpine
    name: cmake
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
