package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: gobject-introspection-dev
    version: '>=0'
  - category: alpine
    name: musl-utils
    version: '>=0'
  - category: alpine
    name: meson
    version: '>=0'
  - category: alpine
    name: gtk-doc
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
