package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: brotli-dev
    version: '>=0'
  - category: alpine
    name: c-ares-dev
    version: '>=0'
  - category: alpine
    name: libuv-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: nghttp2-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: python3
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
