package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: libxslt-dev
    version: '>=0'
  - category: alpine
    name: perl-xml-sax
    version: '>=0'
  - category: alpine
    name: perl-xml-sax
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
