package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: libestr-dev
    version: '>=0'
  - category: alpine
    name: libfastjson-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
