package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: python3
    version: '>=0'
  - category: alpine
    name: sqlite-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: curl-dev
    version: '>=0'
  - category: alpine
    name: gmp-dev
    version: '>=0'
  - category: alpine
    name: libcap-dev
    version: '>=0'
  - category: alpine
    name: gettext-dev
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
