package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: xz-dev
    version: '>=0'
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: coreutils
    version: '>=0'
  - category: alpine
    name: bash
    version: '>=0'
  - category: alpine
    name: syslinux
    version: '>=0'
  - category: alpine
    name: xorriso
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
