package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: linux-pam-dev
    version: '>=0'
  - category: alpine
    name: postgresql-dev
    version: '>=0'
  - category: alpine
    name: libgcrypt-dev
    version: '>=0'
  - category: alpine
    name: bsd-compat-headers
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
