package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: python3
    version: '>=0'
  - category: alpine
    name: cairo-dev
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: glib-dev
    version: '>=0'
  - category: alpine
    name: libffi-dev
    version: '>=0'
  - category: alpine
    name: flex
    version: '>=0'
  - category: alpine
    name: bison
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: meson
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
