package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: alsa-lib-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: python3
    version: '>=0'
  - category: alpine
    name: flac-dev
    version: '>=0'
  - category: alpine
    name: libvorbis-dev
    version: '>=0'
  - category: alpine
    name: libogg-dev
    version: '>=0'
  - category: alpine
    name: opus-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
