package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: pcre-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: libedit-dev
    version: '>=0'
  - category: alpine
    name: py3-docutils
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: libunwind-dev
    version: '>=0'
  - category: alpine
    name: py3-sphinx
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
