package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: attr-dev
    version: '>=0'
  - category: alpine
    name: curl-dev
    version: '>=0'
  - category: alpine
    name: geoip-dev
    version: '>=0'
  - category: alpine
    name: jansson-dev
    version: '>=0'
  - category: alpine
    name: libcap-dev
    version: '>=0'
  - category: alpine
    name: libucontext-dev
    version: '>=0'
  - category: alpine
    name: linux-headers
    version: '>=0'
  - category: alpine
    name: linux-pam-dev
    version: '>=0'
  - category: alpine
    name: libxml2-dev
    version: '>=0'
  - category: alpine
    name: libxslt-dev
    version: '>=0'
  - category: alpine
    name: lua5.3-dev
    version: '>=0'
  - category: alpine
    name: paxmark
    version: '>=0'
  - category: alpine
    name: pcre-dev
    version: '>=0'
  - category: alpine
    name: postgresql-dev
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: zeromq-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
