package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: curl-dev
    version: '>=0'
  - category: alpine
    name: expat-dev
    version: '>=0'
  - category: alpine
    name: perl-dev
    version: '>=0'
  - category: alpine
    name: python3-dev
    version: '>=0'
  - category: alpine
    name: pcre2-dev
    version: '>=0'
  - category: alpine
    name: asciidoc
    version: '>=0'
  - category: alpine
    name: xmlto
    version: '>=0'
  - category: alpine
    name: perl-error
    version: '>=0'
  - category: alpine
    name: tcl
    version: '>=0'
  - category: alpine
    name: tk
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
