package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: e2fsprogs-dev
    version: '>=0'
  - category: alpine
    name: ntfs-3g-dev
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: zlib-dev
    version: '>=0'
  - category: alpine
    name: libjpeg-turbo-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
