package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: openssl-dev
    version: '>=0'
  - category: alpine
    name: e2fsprogs-dev
    version: '>=0'
  - category: alpine
    name: autoconf
    version: '>=0'
  - category: alpine
    name: automake
    version: '>=0'
  - category: alpine
    name: bash
    version: '>=0'
  - category: alpine
    name: gawk
    version: '>=0'
  - category: alpine
    name: libtool
    version: '>=0'
  - category: alpine
    name: ncurses-dev
    version: '>=0'
  - category: alpine
    name: perl
    version: '>=0'
  - category: alpine
    name: readline-dev
    version: '>=0'
  - category: alpine
    name: sqlite-dev
    version: '>=0'
  - category: alpine
    name: texinfo
    version: '>=0'
  - category: alpine
    name: perl-json
    version: '>=0'
  - category: alpine
    name: gdbm-dev
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
