package_dir: /luetbuild/pkg/{{.Values.name}}
steps:
  - sh build.sh
requires:
  - category: alpine
    name: py3-setuptools
    version: '>=0'
  - category: alpine
    name: py3-py
    version: '>=0'
  - category: development
    name: toolchain
    version: '>=0'
